- name : Install Python
  ansible.builtin.import_role :
    name : common
    tasks_from : python-install

- name : setup user/app directory roboshop
  ansible.builtin.import_role :
    name : common
    tasks_from : setup-user

- name : Install dependencies
  ansible.builtin.shell : pip3.6 install -r requirements.txt
  args :
    chdir : /app

- name : systemd setup and restart
  ansible.builtin.import_role :
    name : common
    tasks_from : systemd-setup
