- name : copy mongo repo in yum.repos.d
  ansible.builtin.copy :
    src : mongo.repo
    dest : /etc/yum.repos.d/mongo.repo
    remote_src: yes

- name :  mongodb client software installation
  ansible.builtin.yum :
    name : mongodb-org-shell
    state : installed

- name: load catalogue data(schema)
  ansible.builtin.command: mongo --host mongo.devopspractice.tech < /app/schema/catalogue.js